FROM centos:centos7
MAINTAINER Gayatri S Ajith <gayatri@schogini.com>

# Reference: https://github.com/orboan-docker/docker-centos-supervisor-ssh/blob/master/Dockerfile

RUN yum update -y && yum install -y nano curl wget git tree openssh-server python-setuptools epel-release supervisor
RUN yum update -y && \
    yum install -y epel-release && \
    yum install -y \
      iproute \
      python-setuptools \
      hostname \
      inotify-tools \
      yum-utils \
      which \
      jq \
      python-meld3 \
      python-pip && \
    yum clean all
RUN pip install supervisor
RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

RUN yum update -y && \
    yum install -y nano curl wget git tree openssh-server openssh-clients sudo 

RUN mkdir -p /run/sshd

# - Generate keys for ssh. 
# (This is usually done by systemd when sshd service is started)
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' \
&& ssh-keygen -t dsa  -f /etc/ssh/ssh_host_dsa_key -N '' \
&& ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' \
&& chmod 600 /etc/ssh/*

# - Adding keyfiles configuration
RUN \
  sed -ri 's/^HostKey\ \/etc\/ssh\/ssh_host_ed25519_key/#HostKey\ \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config && \
  sed -ri 's/^#HostKey\ \/etc\/ssh\/ssh_host_dsa_key/HostKey\ \/etc\/ssh\/ssh_host_dsa_key/g' /etc/ssh/sshd_config && \
  sed -ri 's/^#HostKey\ \/etc\/ssh\/ssh_host_rsa_key/HostKey\ \/etc\/ssh\/ssh_host_rsa_key/g' /etc/ssh/sshd_config && \
  sed -ri 's/^#HostKey\ \/etc\/ssh\/ssh_host_ecdsa_key/HostKey\ \/etc\/ssh\/ssh_host_ecdsa_key/g' /etc/ssh/sshd_config && \
  sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

RUN sed -ri 's/^#IgnoreUserKnownHosts\s+.*/IgnoreUserKnownHosts yes/' /etc/ssh/sshd_config && \
    sed -ri 's/^PermitEmptyPasswords\s+.*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config && \
    sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && \
    sed -ri 's/^#PermitEmptyPasswords\s+.*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config && \
    sed -ri 's/^#PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/^#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config && \
    echo "ClientAliveInterval 120" >> /etc/ssh/sshd_config && \
    echo "ClientAliveCountMax 720" >> /etc/ssh/sshd_config && \
    echo "root:sree1234"|chpasswd

RUN useradd --create-home --shell /bin/bash ubuntu
RUN echo 'ubuntu:aspe1234' | chpasswd

RUN ls -l /usr/bin/python
RUN which supervisord
RUN ls -l /etc/supervisor

# - Clean YUM caches to minimise Docker image size...
RUN yum clean all && rm -rf /tmp/yum*

CMD ["/usr/bin/supervisord"]
