FROM gayatrisa/mycentos:7-with-ssh
MAINTAINER Gayatri S Ajith <gayatri.sa@gmail.com>

RUN yum update -y && yum install -y nano curl wget git tree
RUN rpm -Uvh https://yum.puppet.com/puppet5-release-el-7.noarch.rpm
RUN yum update -y && yum install -y puppet-agent

RUN echo "export PATH=/opt/puppetlabs/bin:${PATH}" >> /root/.bashrc

COPY set-puppet-conf.sh /tmp/set-puppet-conf.sh
RUN chmod u+x /tmp/set-puppet-conf.sh
COPY install.sh /tmp/install.sh
RUN chmod u+x /tmp/install.sh

ENTRYPOINT ["/tmp/install.sh"]
