FROM gayatrisa/myubuntu:20.04-with-ssh
MAINTAINER Gayatri S Ajith <gayatri.sa@gmail.com>

# to fix ohai error: WARN: Plugin Network: unable to detect ipaddress
RUN apt-get update && apt-get install -y iproute2
